name: countries
description: pick countries with dialog, bottom sheet or dropdown, access to countries code and flags
version: 0.0.3
homepage: https://github.com/appsah/countries

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  lint: ^1.5.2

flutter:
  assets:
    - assets/
